# log_level : 50=CRITICAL, 40=ERROR, 30=WARNING, 20=INFO, 10=DEBUG, 0=NOTSET
log_level: 20

# Experiment
seed: 42

# Display
model_summary: True
tensorboard: True

# Data
batch_size: 32
img_size: 224
channels: 3
nb_saved_augmented_img: 16

# CV
n_folds: 1
stratified: True
val_size: 0.2

# Base network
base: "DenseNet121"
init_weights: "imagenet"
include_top: False
unfreeze_layers: -1

# Network head
dropout: 0.2

# Optimizer
optimizer: "Nadam"
lr: "RampUp"
lr_start: 0.00001
### for CosineDecay, CosineDecayRestarts
lr_decay_epochs: 10
lr_alpha: 0.1 # Minimum LR as a fraction of initial_learning_rate
### for CosineDecayRestarts
lr_restart_epoch_multiplier: 1 # Each new warm restart runs for lr_restart_epoch_multiplier times more epochs
lr_restart_multiplier: 0.8 # Each new warm restart runs with lr_restart_multiplier smaller initial LR
### for PiecewiseConstantDecay
lr_custom_boundaries: [3, 6, 9]
lr_custom_values: [0.001, 0.0006, 0.0003, 0.0001]
### for RampUp
lr_rampup_max: 0.0001
lr_rampup_min: 0.00002
lr_rampup_epochs: 3
lr_rampup_sustain_epochs: 0
lr_rampup_decay_factor: .8

# Training
epochs: 15
early_stopping_epochs: 4
restore_best_after_training: True
loss: "SparseCategoricalCrossentropy"
metrics: "SparseCategoricalAccuracy"
balanced_weights: False
checkpoints: True

# Warmup
warmup_epochs: 0
warmup_lr: 0.0005

# Augmentations - train
train_random_flip_left_right: True
train_random_flip_up_down: True
train_rot90: True
train_random_brightness: 0.1 # 0=do nothing; 0=default brightness; bigger=brighter
train_random_hue: 0.1 # 0=do nothing; 0=default hue; 0.5=max allowed
train_random_saturation: [0.7, 1.3] # [0, 0]=do nothing; 1=starting saturation; Center around 1 for balanced mix
train_random_contrast: [0.7, 1.3] # [0, 0]=do nothing; 1=starting contrast; Center around 1 for balanced mix
train_random_crop: 0 # in pixels; 0=do nothing
train_central_crop: 0 # in [0:1]; 0=do nothing, 1=nothing left
train_cutmix_proba: 0. # in [0.:1.]; 0.=do nothing, 1.=all images use cutmix
train_mixup_proba: 0. # in [0.:1.]; 0.=do nothing, 1.=all images use mixup
