# log_level : 50=CRITICAL, 40=ERROR, 30=WARNING, 20=INFO, 10=DEBUG, 0=NOTSET
log_level: 20

# Startup
mixed_precision: True
path_to_cuda: 'C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.4'
seed: 42
xla: True

# Display
model_summary: False
tensorboard: False

# Data
batch_size: 32
channels: 3
img_size_y: 224
img_size_x: 224
nb_saved_augmented_img: 16

# CV
first_fold_only: True
n_folds: 5
#val_size: 0.2

# Base network
base: "DenseNet121"
include_top: False
init_weights: "imagenet"
unfreeze_layers: -1

# Network head
dropout: 0.1

# Optimizer
optimizer: "Adam"
### for AdamW, LAMB, RectifiedAdam
weight_decay: 0.0001

# Learning rate
lr: "RampUp"
lr_start: 0.00001
### for CosineDecay, CosineDecayRestarts
lr_alpha: 0.1 # Minimum LR as a fraction of initial_learning_rate
lr_decay_epochs: 10
### for CosineDecayRestarts
lr_restart_epoch_multiplier: 1 # Each new warm restart runs for lr_restart_epoch_multiplier times more epochs
lr_restart_multiplier: 0.8 # Each new warm restart runs with lr_restart_multiplier smaller initial LR
### for PiecewiseConstantDecay
lr_custom_boundaries: [3, 6, 9]
lr_custom_values: [0.001, 0.0006, 0.0003, 0.0001]
### for RampUp
lr_rampup_decay_factor: .8
lr_rampup_epochs: 3
lr_rampup_max: 0.0001
lr_rampup_min: 0.00002
lr_rampup_sustain_epochs: 0

# Warmup
warmup_epochs: 0
warmup_lr: 0.0005

# Training
balanced_weights: False
checkpoints: True
early_stopping_epochs: 4
epochs: 20
label_smoothing: 0. # [0,1] 0=no smoothing. >0=larger values squeeze labels towards 0.5
loss: "CategoricalCrossentropy"
metrics: "CategoricalAccuracy"
onehot: True
restore_best_after_training: True

# Augmentations - train
train_cutmix_proba: 0. # in [0.:1.]; 0.=do nothing, 1.=all images use cutmix
train_mixup_proba: 0. # in [0.:1.]; 0.=do nothing, 1.=all images use mixup

train_blur: [0., 0.] # [max € [3,inf], proba € [0:1]]
train_centercrop: [0., 0.] # crop_proportion € [0, 100], proba € [0:1]
train_clahe: [0, 0, 0] # [max € [1,inf], tile_grid_size € [1,inf], proba € [0:1]]
train_coarse_dropout: [0, 0, 0, 0] # [min_nb_holes € [1,inf], max_nb_holes € [min_nb_holes,inf], hole_size € [1,imh_size], proba € [0:1]]
train_crop: [0, 0, 0, 0, 0] # xmin/max ymin/max € [1,img_size], proba € [0:1]
train_horizontal_flip: 0. # proba € [0:1]
train_hue_sat_value: [0, 0, 0, 0] # [shift_limit, sat_shift, val_shift € [0,inf], proba € [0:1]]
train_random_brightness: [0., 0.] # [factor, proba € [0:1]]
train_random_contrast: [0., 0.] # [factor, proba € [0:1]]
train_random_fog: [0, 0, 0, 0] # [intensity_low, intensity_high € [0,1], alpha_coef € [0,1], proba € [0:1]]
train_random_grid_shuffle: [0, 0, 0] # [vertical_split, horiz_split € [1,5], proba € [0:1]]
train_random_resized_crop: [0, 0, 0] # [scale_min, scale_max € [0,1], proba € [0:1]]
train_rotate: [90, 0.9] # angle € [0:180], proba € [0:1]
train_vertical_flip: 0. # proba € [0:1]

# Augmentations - test
test_cutmix_proba: 0. # in [0.:1.]; 0.=do nothing, 1.=all images use cutmix
test_mixup_proba: 0. # in [0.:1.]; 0.=do nothing, 1.=all images use mixup

test_blur: [0., 0.] # [max € [3,inf], proba € [0:1]]
test_centercrop: [0., 0.] # crop_proportion € [0, 100], proba € [0:1]
test_clahe: [0, 0, 0] # [max € [1,inf], tile_grid_size € [1,inf], proba € [0:1]]
test_coarse_dropout: [0, 0, 0, 0] # [min_nb_holes € [1,inf], max_nb_holes € [min_nb_holes,inf], hole_size € [1,imh_size], proba € [0:1]]
test_crop: [0, 0, 0, 0, 0] # xmin/max ymin/max € [1,img_size], proba € [0:1]
test_horizontal_flip: 0. # proba € [0:1]
test_hue_sat_value: [0, 0, 0, 0] # [shift_limit, sat_shift, val_shift € [0,inf], proba € [0:1]]
test_random_brightness: [0., 0.] # [factor, proba € [0:1]]
test_random_contrast: [0., 0.] # [factor, proba € [0:1]]
test_random_fog: [0, 0, 0, 0] # [intensity_low, intensity_high € [0,1], alpha_coef € [0,1], proba € [0:1]]
test_random_grid_shuffle: [0, 0, 0] # [vertical_split, horiz_split € [1,5], proba € [0:1]]
test_random_resized_crop: [0, 0, 0] # [scale_min, scale_max € [0,1], proba € [0:1]]
test_rotate: [30, 0.5] # angle € [0:180], proba € [0:1]
test_vertical_flip: 0. # proba € [0:1]
